apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helpernote-backend
  namespace: helpernote
  labels:
    app: helpernote
    component: backend
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: backend-metrics
  namespace: helpernote
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
