---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: helpernote
spec:
  encryptedData:
    access-key: AgA3P5em+zC7Drl1RwHKuds1HiFBNP/33jR+++R9efvxbUffZat7N845GxTkxZhBFgIzOUndjWN0kYsGuMGzCxEAaCnp9UvfBqrEw41OJ2WEuwRpNFmrMauKj1bToLBRgybNMRtmT5aIV0VUa1y+IdM/T3X7AtF+c1zu/lh5jDeUwqA/OHny12zGQutoEoQhR88vDRx6UN1XpUfX744h28T9ZBxKNNzPh7gvSCJ9zLltMXcbeiiCnfXrzgxMOeAJwYJhSWEkI96XQQXvNDyUHG840c5jeBFByNOf4JBW4901XvfzghoRCqMPVvo8J9PILfzd7C1Tl36Oc5n6BiGws4NxgpI7BEGG7Xgqe40By04qRHWnBWgLBXkwFnU6VROFDiinDHMQXOLtPEOPNB7pT70r5DKdrhcqKmChorQkZ1tL7CLWmw1eRLQypEZt5sFi9IpweBlSSgcTG0Gi/EOOPQa/sfrKdNgKCs3WE+yb3lSD9JffIFKSa+ZV2lezB99ZJ41+ZLiTfnNswMPRWgLcq8q79mh4RqUruBSWR4wxg1YOEpiFzjIlm8eRJclkDhzfF2oG5TcrK39DtYmUPrQckjVipinp5W4Z7OdqiJ1m/gSTlTuHQxW6q1SIRboBKztdDZtaEz6+cqYAxAVjGUvdDgkQI6aH+N3EZpNHMTPP73mJDvgSGpLULhAOf9ErLAD3gQ7r69r3WIhSoMvdus/frYSHAwk6a12QH9TyLhLSxx2m5Q==
    secret-key: AgCyYI8jJAT7o8K2qpa3wxWGeSpx79Q8BvV8bY4bMeFByXHF9KgFw7milKBzKPGBZwynNOPphZy/pWZeC9PXm+Fs+DKqxnNyopEj73tQ4pjAZ42EN01MQPyscFv9scBDWKBhlvDeNXy0wyLdJofyeOBvrEzl4bPQzDissRwdlmqhhwPXnw8Evs1lWPuACSDgiyxbtatyg2DzmTKyc1POFZgzrG5IPGk5BpWolV9kdKbm8YKfX88urVdnuYcsB3MP7NYVrxGkRGeUPHfdxof42QM6h8gQwb+acXxF73xck4OsURdRTNxiTdyx8aGrmjvhHfNvA+n/YM3C8uZavd+pOOjlMgsjggEJfF0spd+6P0/HlukM87XzULw7K8J/0CPH0qzUjwH/SChyWahqenyRybkAdNDHw1KeJhb3cb0X/axbp6bQD2LAXQfQq/ql32s9dCANC4MkvkSxJyG5wjWnKM7ogxI/1896ieIONfOyYekrymei0PiNj5n4eOCocy/Hjp5orYg8WZNeS9fPo0bE6f4KayagRnlounEcdz96yKD88UOcXMqCpYncEdrhpdHy26kk1QQkcsZ8gr6slyX2SOXv1IYPhzEwHDN0TmPHuTiSu3O5gcrSSCuono11kwGYbaPixNeImulAgmBhDe9AqaULt8HkDuZaSya6MkQ6U2ZkXBacg7n5c442g+eSuJQfxLFA0umlt7En4T+km32yf7N8QcXvoJmLfV+FvB5Ozx0ICY4WOHcLHXQPkQO31uDC65C37EbtoJCT2W2GYbHPUnFf
  template:
    metadata:
      name: minio-secret
      namespace: helpernote
    type: Opaque
