---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: helpernote
spec:
  encryptedData:
    access-key: AgBsrTzuB3DdLDgf9hstY7IOgRJQzY6oHofTRef/e0zXHpVhb8lAKwVW7f7HYcJFET1MVU6KeBlvAYtoeLIyFUbbZbVCQ1Mue/rqr/QwGCp7kxrGwTpXBak/3BxE/kXuSBo/OI2I0rwogAzN++AWzS+p6RAKSf7+wrp+4z3nWtrsk4DeEISMm2vCuheVLzvojXyAcHka7ChfXlwbehfkAPWMQ2VUgFryBKRDiotcmd+wcpYYPnieqwm3kXa5Ry/+H/hFDwFRFW1/0Xd41lHJRdf/xmOM2XkfZycuP0wMpL6FevB0ynLGenkRHi0/7QDqwTUNYCDmlkL1FVfw4+AE7/2m46lwvDddC+33nt4mJSvAMSF0cZqx0ILceVhCYfZUfTdDzv9bANDSwqzofYEYtkEWM8lYTYTuPALCXByPjClfziBnAO4vkUWlCtVs5zubDrWzaor7hShm2Dxdfx5/WzRILBMWHG8McsqtzuiLy70k/NczhAQs5zgPhRRUpXMgdB3Q6EBZ/8Aenhf8uGZs6+vIYInvlKAf1XITlKWAGVqlFRTXf/AfVncjpap3FR9uqTdfcGDgyPz6i46Q8NYZMWqRtljE0LUG3L8LLhl+SdoL6z12jo31ktOBW1TUReMhwlCB1V7rqcRIXABh6RK1LoEJq07IaW0VD70poYfn0K8bK/gOCnRLBMnZ3SfVUnLgzzw7g6qpVSJodU2Z6EagnDITDg/hFAcu/NkS3AOCAkxWKg==
    secret-key: AgAxGwZHlpO8xsTynSCL/z+LBKHwvYhJ+fBiUsFRNvwl0TKPskz/BAIw4Pt8P4OOn7VIltisxAvOAcOfQ4HeVCpE+whpM8sYdF0XXJ6unId1LV8pX64Sq7ts0VOpFKhVFRpCoC7Oa+iQ2ZtB6M8SDrA9buifxwy182G2wfAGlMlG1Azvb3twnEJ5m8EwLev4OTCOT4+pnkTU0AVgLtu2QkzrlPvv04O7BBX8AiOJ6DbjzKsm3foRMZpSK4q232Db8Gb+WE0H/K1Nxc1xn0iKCQxcK+kF6+wlMJfNu3ufg1lCuf/kTUI7Hp3eqslQObp9lqGdX1GxGCqX6SxE2IqtZPIn8T2v+MEf97rQOH+5XUVjavGWI/W4PEdHmESt0enMzxL7j3o3V/g73akU67whD1/a34RpuXBcVzgN10lOWmcobKTi9Jrz55aT0hyc1Hvlk5UPKINn2e1sol80b2FTiO2dp+xJEgZy+7ZmzJIkc7TwAnLAlzFwAx2a2j3P9yE71HR6PVkZlImKbDny/EoZiL5DF+G88obQZ6G2xwHDoAUnWo/c1x5LU2mgPEXzWAIH2YhKq1xG70lR/dIxfY44aS4nJiL07HYL8Rz0ESHYZyIVe5W9eSdbFgXhNtiUTmixp4pT6biMASuQHPUopaP4DivBhxjU0/2BqKUN7njY+OXD4oDF+UhP22ZOJIe36jRabIF8hgzUAnCcNe39FBd2I2taAeSNG7Z4k7MLVm3Y6YfyC2bvajQVNI/c2z9+
  template:
    metadata:
      name: minio-secret
      namespace: helpernote
