version: 2
updates:
  # Backend: Rust/Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    reviewers:
      - "e16tae"
    labels:
      - "dependencies"
      - "backend"
      - "rust"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Frontend: npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 10
    reviewers:
      - "e16tae"
    labels:
      - "dependencies"
      - "frontend"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor and patch updates
    groups:
      next:
        patterns:
          - "next"
          - "next-*"
      react:
        patterns:
          - "react"
          - "react-*"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "e16tae"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "e16tae"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    reviewers:
      - "e16tae"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
