apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            # Update secret references to use prod- prefix
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prod-backend-secret
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: prod-backend-secret
                  key: jwt-secret
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: prod-minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: prod-minio-secret
                  key: secret-key
