apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use 'resources' instead of deprecated 'bases'
resources:
  - ../../base
  - ../../sealed-secrets

namePrefix: prod-

# Use labels instead of commonLabels to avoid patch conflicts
labels:
  - pairs:
      environment: production

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 3

images:
  - name: ghcr.io/e16tae/helpernote-backend
    newName: ghcr.io/e16tae/helpernote-backend
    newTag: main-0d4f1ff
  - name: ghcr.io/e16tae/helpernote-frontend
    newName: ghcr.io/e16tae/helpernote-frontend
    newTag: main-0d4f1ff

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: helpernote-ingress
    options:
      allowNameChange: true
  - path: backend-resources-patch.yaml
    target:
      kind: Deployment
      name: backend
    options:
      allowNameChange: true
  - path: frontend-resources-patch.yaml
    target:
      kind: Deployment
      name: frontend
    options:
      allowNameChange: true
  - path: backend-imagepullsecret-patch.yaml
    target:
      kind: Deployment
      name: backend
    options:
      allowNameChange: true
  - path: frontend-imagepullsecret-patch.yaml
    target:
      kind: Deployment
      name: frontend
    options:
      allowNameChange: true
  - path: sealedsecret-backend-template-patch.yaml
    target:
      kind: SealedSecret
      name: backend-secret
    options:
      allowNameChange: true
  - path: sealedsecret-minio-template-patch.yaml
    target:
      kind: SealedSecret
      name: minio-secret
    options:
      allowNameChange: true
  - path: sealedsecret-postgres-template-patch.yaml
    target:
      kind: SealedSecret
      name: postgres-secret
    options:
      allowNameChange: true
