apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use 'resources' instead of deprecated 'bases'
resources:
  - ../../base

namePrefix: prod-

# Use labels instead of commonLabels to avoid patch conflicts
labels:
  - pairs:
      environment: production

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 3

images:
  - name: ghcr.io/e16tae/helpernote-backend
    newName: ghcr.io/e16tae/helpernote-backend
    newTag: main-463ac21c41abfbe6837dffcd454214b218dca12a
  - name: ghcr.io/e16tae/helpernote-frontend
    newName: ghcr.io/e16tae/helpernote-frontend
    newTag: main-463ac21c41abfbe6837dffcd454214b218dca12a

# patchesStrategicMerge is deprecated but still widely used and supported
# It handles multi-document YAML files better than the new patches format
patchesStrategicMerge:
  - resources-patch.yaml
  - ingress-patch.yaml
  - imagepullsecrets-patch.yaml
