apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use 'resources' instead of deprecated 'bases'
resources:
  - ../../base
  - ../../sealed-secrets

# namePrefix removed - SealedSecrets are encrypted for unprefixed names
# Use labels and namespace for environment isolation instead

# Use labels instead of commonLabels to avoid patch conflicts
labels:
  - pairs:
      environment: production

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 3

images:
  - name: ghcr.io/e16tae/helpernote-backend
    newName: ghcr.io/e16tae/helpernote-backend
    newTag: main-d7763c1
  - name: ghcr.io/e16tae/helpernote-frontend
    newName: ghcr.io/e16tae/helpernote-frontend
    newTag: main-d7763c1

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: helpernote-ingress
    options:
      allowNameChange: true
  - path: backend-resources-patch.yaml
    target:
      kind: Deployment
      name: backend
    options:
      allowNameChange: true
  - path: frontend-resources-patch.yaml
    target:
      kind: Deployment
      name: frontend
    options:
      allowNameChange: true
  - path: backend-imagepullsecret-patch.yaml
    target:
      kind: Deployment
      name: backend
    options:
      allowNameChange: true
  - path: frontend-imagepullsecret-patch.yaml
    target:
      kind: Deployment
      name: frontend
    options:
      allowNameChange: true
  # Fix secret references to use prod- prefix
  - path: backend-secret-refs-patch.yaml
    target:
      kind: Deployment
      name: backend
    options:
      allowNameChange: true
  - path: postgres-secret-refs-patch.yaml
    target:
      kind: StatefulSet
      name: postgres
    options:
      allowNameChange: true
  - path: minio-secret-refs-patch.yaml
    target:
      kind: Deployment
      name: minio
    options:
      allowNameChange: true
