apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use 'resources' instead of deprecated 'bases'
resources:
  - ../../base
  - ../../sealed-secrets

namePrefix: prod-

# Use labels instead of commonLabels to avoid patch conflicts
labels:
  - pairs:
      environment: production

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 3

images:
  - name: ghcr.io/e16tae/helpernote-backend
    newName: ghcr.io/e16tae/helpernote-backend
    newTag: main-b22480e
  - name: ghcr.io/e16tae/helpernote-frontend
    newName: ghcr.io/e16tae/helpernote-frontend
    newTag: main-b22480e

# patchesStrategicMerge is deprecated but still widely used and supported
# It handles multi-document YAML files better than the new patches format
patchesStrategicMerge:
  - resources-patch.yaml
  - ingress-patch.yaml
  - imagepullsecrets-patch.yaml

patchesJson6902:
  - target:
      group: bitnami.com
      version: v1alpha1
      kind: SealedSecret
      name: prod-backend-secret
    path: sealedsecret-backend-name-patch.yaml
  - target:
      group: bitnami.com
      version: v1alpha1
      kind: SealedSecret
      name: prod-minio-secret
    path: sealedsecret-minio-name-patch.yaml
  - target:
      group: bitnami.com
      version: v1alpha1
      kind: SealedSecret
      name: prod-postgres-secret
    path: sealedsecret-postgres-name-patch.yaml
