apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      containers:
        - name: minio
          env:
            # Update secret references to use prod- prefix
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: prod-minio-secret
                  key: access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-minio-secret
                  key: secret-key
