apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          env:
            # Update secret references to use prod- prefix
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: prod-postgres-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: prod-postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-postgres-secret
                  key: password
