apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: helpernote
spec:
  template:
    metadata:
      name: prod-backend-secret
      namespace: helpernote
