apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpernote

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - minio-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - apex-redirect-ingress.yaml

commonLabels:
  app.kubernetes.io/name: helpernote
  app.kubernetes.io/managed-by: kustomize
