apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpernote

resources:
  - namespace.yaml
  - configmap.yaml
  # ⚠️  민감한 값은 Sealed Secrets를 사용해 k8s/sealed-secrets/에 커밋하세요.
  - postgres-statefulset.yaml
  - minio-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - apex-redirect-ingress.yaml

commonLabels:
  app.kubernetes.io/name: helpernote
  app.kubernetes.io/managed-by: kustomize
