apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1

images:
  - name: helpernote-backend
    newTag: dev-latest
  - name: helpernote-frontend
    newTag: dev-latest

patchesStrategicMerge:
  - ingress-patch.yaml
